version: '3.8'

services:
  backend:
    build:
      context: ../server
      dockerfile: ../docker/Dockerfile.backend
    container_name: 1000-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=http://localhost:80
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "run", "-e", "const res = await fetch('http://localhost:3000/health'); process.exit(res.ok ? 0 : 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      args:
        VITE_API_URL: http://localhost:3000
    container_name: 1000-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend: 