[build]
builder = "DOCKERFILE"
dockerfilePath = "./docker/Dockerfile.frontend"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 